# Generated by Django 4.2.1 on 2023-05-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='High',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trading',
            name='Low',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
