# Generated by Django 4.2.1 on 2023-06-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
