# Generated by Django 4.2.1 on 2023-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_userprofiles_user_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
